In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5,6,7,8])
b = np.array([8,7,6,5,4,3,2,1])
print(a)
print(b)

[1 2 3 4 5 6 7 8]
[8 7 6 5 4 3 2 1]


In [4]:
type(a)

numpy.ndarray

In [5]:
print(a + b)
print(a - b)
print(a * b)

[9 9 9 9 9 9 9 9]
[-7 -5 -3 -1  1  3  5  7]
[ 8 14 18 20 20 18 14  8]


In [6]:
# creating a 2D array
a2 = np.array([[1,2],[3,4]])
print(a2)

[[1 2]
 [3 4]]


In [ ]:
#3d array
a3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a3)